/**
 * twig.js
 * https://github.com/schmittjoh/twig.js
 *
 * (C) 2011 Johannes M. Schmitt <schmittjoh@gmail.com>
 * Licensed under the Apache 2.0 License.
 *
 * Portions of this code are from the Google Closure Library received
 * from the Closure Authors under the Apache 2.0 License.
 */
(function() {var g=null,h=!1,i,j=this;function l(a,c,b){a=a.split(".");b=b||j;!(a[0]in b)&&b.execScript&&b.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&c!==void 0?b[d]=c:b=b[d]?b[d]:b[d]={}}
function n(a){var c=typeof a;if(c=="object")if(a){if(a instanceof Array)return"array";if(a instanceof Object)return c;var b=Object.prototype.toString.call(a);if(b=="[object Window]")return"object";if(b=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(b=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(c=="function"&&typeof a.call=="undefined")return"object";return c}function o(a){return n(a)=="array"}function r(a){return typeof a=="string"}function s(a){a=n(a);return a=="object"||a=="array"||a=="function"}var t="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),u=0;function v(a,c,b){return a.call.apply(a.bind,arguments)}
function w(a,c,b){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var b=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(b,d);return a.apply(c,b)}}return function(){return a.apply(c,arguments)}}function x(a,c,b){x=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?v:w;return x.apply(g,arguments)}function y(a,c){l(a,c,void 0)};var z=/&/g,A=/</g,B=/>/g,C=/\"/g,E=/[&<>\"]/,F={"\x00":"\\0","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\x0B",'"':'\\"',"\\":"\\\\"},G={"'":"\\'"};var H;(H="ScriptEngine"in j&&j.ScriptEngine()=="JScript")&&(j.ScriptEngineMajorVersion(),j.ScriptEngineMinorVersion(),j.ScriptEngineBuildVersion());function I(a,c){this.a=H?[]:"";a!=g&&this.append.apply(this,arguments)}H?(I.prototype.c=0,I.prototype.append=function(a,c,b){c==g?this.a[this.c++]=a:(this.a.push.apply(this.a,arguments),this.c=this.a.length);return this}):I.prototype.append=function(a,c,b){this.a+=a;if(c!=g)for(var d=1;d<arguments.length;d++)this.a+=arguments[d];return this};I.prototype.clear=function(){H?this.c=this.a.length=0:this.a=""};I.prototype.toString=function(){if(H){var a=this.a.join("");this.clear();a&&this.append(a);return a}return this.a};function J(a,c){for(var b in a)if(c.call(void 0,a[b],b,a))return b}var K="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(",");function L(a,c){for(var b,d,f=1;f<arguments.length;f++){d=arguments[f];for(b in d)a[b]=d[b];for(var e=0;e<K.length;e++)b=K[e],Object.prototype.hasOwnProperty.call(d,b)&&(a[b]=d[b])}};var M=Array.prototype,N=M.indexOf?function(a,c,b){return M.indexOf.call(a,c,b)}:function(a,c,b){b=b==g?0:b<0?Math.max(0,a.length+b):b;if(r(a))return!r(c)||c.length!=1?-1:a.indexOf(c,b);for(;b<a.length;b++)if(b in a&&a[b]===c)return b;return-1},O=M.forEach?function(a,c,b){M.forEach.call(a,c,b)}:function(a,c,b){for(var d=a.length,f=r(a)?a.split(""):a,e=0;e<d;e++)e in f&&c.call(b,f[e],e,a)};var P=x,t="twig_ui_"+Math.floor(Math.random()*2147483648).toString(36);function Q(a){return g===a||h===a||void 0===a||0===a?!0:R(a)?0===S(a):h}function T(a,c){L.apply(g,Array.prototype.slice.call(arguments,0));return a}function R(a){return o(a)||r(a)||s(a)}function S(a){if(o(a))return a.length;if(r(a))return a.length;if(s(a)){var c=0,b;for(b in a)c++;return c}throw Error(typeof a+" is not countable.");};function U(a){this.env_=a;this.b=[];this.k={}}i=U.prototype;i.n=function(){return this.b};i.r=function(a){this.b=a};i.v=function(a){this.k=a};i.getParent=function(a){a=this.getParent_(a);return h===a?h:this.env_.d(a)};i.q=function(a,c,b){if(a in this.k){var d=new I;this.k[a](d,c,b||{});return d.toString()}d=this.getParent(c);if(h!==d)return d.i(a,c,b);throw Error("The template '"+this.z()+"' has no parent, and no trait defining the block '"+a+"'.");};
i.i=function(a,c,b){if(b&&a in b){var d=new I,f=b[a];delete b[a];f(d,c,b);return d.toString()}if(a in this.b)return d=new I,this.b[a](d,c,b||{}),d.toString();d=this.getParent(c);return h!==d?d.i(a,c,b):""};i.h=function(a,c){var b=new I;this.render_(b,a||{},c||{});return b.toString()};function V(){this.f={};this.g={};this.j={};this.e={};this.l={};this.w="UTF-8"}i=V.prototype;i.h=function(a,c){var b=this.d(a);return b.h.call(b,T({},this.l,c||{}))};i.filter=function(a,c,b){if(!(a in this.f))throw Error("The filter '"+a+"' does not exist.");return this.f[a].apply(g,Array.prototype.slice.call(arguments,1))};i.p=function(a,c,b){if(!(a in this.g))throw Error("The function '"+a+"' does not exist.");return this.g[a].apply(g,Array.prototype.slice.call(arguments,1))};
i.test=function(a,c,b){if(!(a in this.j))throw Error("The test '"+a+"' does not exist.");return this.j[a].apply(g,Array.prototype.slice.call(arguments,1))};i.s=function(a,c){this.f[a]=c};i.t=function(a,c){this.g[a]=c};i.u=function(a,c){this.j[a]=c};i.o=function(){return this.l};i.d=function(a){var c=a[t]||(a[t]=++u);if(c in this.e)return this.e[c];a=new a(this);return this.e[c]=a};function W(a){this.m=a}W.prototype.toString=function(){return this.m};window.Twig=new V;y("goog.provide",function(a){l(a)});y("twig.attr",function(a,c,b,d,f){d=d||"any";f=f!==void 0?f:h;if(c in a){if("array"!==d&&n(a[c])=="function")return f?!0:a[c].apply(a,b||[]);if("method"!==d)return f?!0:a[c]}if("array"===d||o(a))return f?h:g;var c=c.toLowerCase(),e="get"+c,k="is"+c;return(c=J(a,function(a,b){b=b.toLowerCase();return b===e||b===k}))&&n(a[c])=="function"?f?!0:a[c].apply(a,b||[]):f?h:g});y("twig.bind",P);
y("twig.inherits",function(a,c){function b(){}b.prototype=c.prototype;a.A=c.prototype;a.prototype=new b});y("twig.extend",T);y("twig.spaceless",function(a){return a.replace(/>[\s\xa0]+</g,"><").replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")});y("twig.range",function(a,c){for(var b=[];a<=c;a+=1)b.push(a);return b});y("twig.contains",function(a,c){var b;if(o(a))b=N(a,c)>=0;else if(r(a))b=a.indexOf(c)!=-1;else a:{for(b in a)if(a[b]==c){b=!0;break a}b=h}return b});y("twig.countable",R);y("twig.count",S);
y("twig.forEach",function(a,c,b){if(o(a))O(a,c,b);else for(var d in a)c.call(b,a[d],d,a)});y("twig.empty",Q);y("twig.filter.capitalize",function(a,c){return c.charAt(0).toUpperCase()+c.substring(1)});
y("twig.filter.escape",function(a,c,b,d,f){var p;if(f&&c instanceof W)return c.toString();c=c==g?"":""+c;if("js"===b){a=""+c;if(a.quote)c=a.quote();else{c=['"'];for(b=0;b<a.length;b++){var e=a.charAt(b),k=e.charCodeAt(0),d=c,f=b+1,m;if(!(m=F[e])){if(!(k>31&&k<127))if(e in G)e=G[e];else if(e in F)p=G[e]=F[e],e=p;else{k=e;m=e.charCodeAt(0);if(m>31&&m<127)k=e;else{if(m<256){if(k="\\x",m<16||m>256)k+="0"}else k="\\u",m<4096&&(k+="0");k+=m.toString(16).toUpperCase()}e=G[e]=k}m=e}d[f]=m}c.push('"');c=c.join("")}return c.substring(1,
c.length-1)}if(!b||"html"===b)return a=c,E.test(a)&&(a.indexOf("&")!=-1&&(a=a.replace(z,"&amp;")),a.indexOf("<")!=-1&&(a=a.replace(A,"&lt;")),a.indexOf(">")!=-1&&(a=a.replace(B,"&gt;")),a.indexOf('"')!=-1&&(a=a.replace(C,"&quot;"))),a;throw Error("The type '"+b+"' is not supported.");});y("twig.filter.length",function(a,c){return S(c)});y("twig.filter.def",function(a,c){return Q(a)?c||"":a});y("twig.filter.replace",function(a,c){for(var b in c)a=a.replace(RegExp(b,"g"),c[b]);return a});
y("twig.filter.date",function(a,c){for(var b=new Date(a),d="",f="Sun,Mon,Tue,Wed,Thu,Fri,Sat".split(","),e="Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday".split(","),k="Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(","),m="January,February,March,April,May,June,July,August,September,October,November,December".split(","),D=new Date(b.getFullYear(),0,1),q=0;q<c.length;q++){var p=c.charAt(q);if(q-1>=0&&c.charAt(q-1)=="\\"&&q-2>=0&&c.charAt(q-2)!="\\")d+=p;else if(p!="\\")switch(p){case "d":d+=
(b.getDate()<10?"0":"")+b.getDate();break;case "D":d+=f[b.getDate()];break;case "j":d+=b.getDate();break;case "l":d+=e[b.getDay()];break;case "N":d+=b.getDay()+1;break;case "S":p="";p=b.getDate()%10==1&&b.getDate()!=11?"st":b.getDate()%10==2&&b.getDate()!=12?"nd":b.getDate()%10==3&&b.getDate()!=13?"rd":"th";d+=p;break;case "w":d+=b.getDay();break;case "z":d+=Math.ceil((b-D)/864E5);break;case "W":d+=Math.ceil(((b-D)/864E5+D.getDay()+1)/7);break;case "F":d+=m[b.getMonth()];break;case "m":d+=(b.getMonth()<
10?"0":"")+(b.getMonth()+1);break;case "M":d+=k[b.getMonth()];break;case "n":d+=b.getMonth()+1;break;case "t":d+=(new Date(b.getFullYear(),b.getMonth(),0)).getDate();break;case "L":d+=(new Date(b.getYear(),1,29)).getDate()==29?1:0;break;case "Y":d+=b.getFullYear();break;case "y":d+=b.getFullYear().toString().substr(2);break;case "a":d+=b.getHours()<12?"am":"pm";break;case "A":d+=b.getHours()<12?"AM":"PM";break;case "g":d+=b.getHours()>12?b.getHours()%12:b.getHours();break;case "G":d+=b.getHours();
break;case "h":p=b.getHours()>12?b.getHours()%12:b.getHours();d+=(p<10?"0":"")+p;break;case "H":d+=(b.getHours()<10?"0":"")+b.getHours();break;case "i":d+=(b.getMinutes()<10?"0":"")+b.getMinutes();break;case "s":d+=(b.getSeconds()<10?"0":"")+b.getSeconds();break;case "Z":d+=-b.getTimezoneOffset()*60;break;case "r":d+=b.toString();break;case "U":d+=b.getTime();break;default:d+=p}}return d});y("twig.StringBuffer",I);I.prototype.append=I.prototype.append;I.prototype.toString=I.prototype.toString;
V.prototype.createTemplate=V.prototype.d;V.prototype.filter=V.prototype.filter;V.prototype.invoke=V.prototype.p;V.prototype.test=V.prototype.test;V.prototype.setFilter=V.prototype.s;V.prototype.setFunction=V.prototype.t;V.prototype.setTest=V.prototype.u;V.prototype.render=V.prototype.h;V.prototype.getGlobals=V.prototype.o;y("twig.Template",U);U.prototype.setTraits=U.prototype.v;U.prototype.setBlocks=U.prototype.r;U.prototype.getBlocks=U.prototype.n;U.prototype.renderParentBlock=U.prototype.q;
U.prototype.renderBlock=U.prototype.i;y("twig.Markup",W);})();
