/**
 * twig.js
 * https://github.com/schmittjoh/twig.js
 *
 * (C) 2011 Johannes M. Schmitt <schmittjoh@gmail.com>
 * Licensed under the Apache 2.0 License.
 *
 * Portions of this code are from the Google Closure Library received
 * from the Closure Authors under the Apache 2.0 License.
 */
(function() {var g=!0,h=null,i=!1,j,k=this;function m(a,b,c){a=a.split(".");c=c||k;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&void 0!==b?c[d]=b:c=c[d]?c[d]:c[d]={}}
function n(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function p(a){return"array"==n(a)}function q(a){return"string"==typeof a}function r(a){var b=typeof a;return"object"==b&&a!=h||"function"==b}var s="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),t=0;function u(a,b,c){return a.call.apply(a.bind,arguments)}
function v(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function w(a,b,c){w=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?u:v;return w.apply(h,arguments)}function x(a,b){m(a,b,void 0)};var y=/&/g,z=/</g,A=/>/g,B=/\"/g,C=/[&<>\"]/,D={"\x00":"\\0","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\"},E={"'":"\\'"};var F;(F="ScriptEngine"in k&&"JScript"==k.ScriptEngine())&&(k.ScriptEngineMajorVersion(),k.ScriptEngineMinorVersion(),k.ScriptEngineBuildVersion());function G(a,b){this.a=F?[]:"";a!=h&&this.append.apply(this,arguments)}F?(G.prototype.c=0,G.prototype.append=function(a,b,c){b==h?this.a[this.c++]=a:(this.a.push.apply(this.a,arguments),this.c=this.a.length);return this}):G.prototype.append=function(a,b,c){this.a+=a;if(b!=h)for(var d=1;d<arguments.length;d++)this.a+=arguments[d];return this};G.prototype.clear=function(){F?this.c=this.a.length=0:this.a=""};G.prototype.toString=function(){if(F){var a=this.a.join("");this.clear();a&&this.append(a);return a}return this.a};function H(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return c}var I="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(",");function J(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<I.length;e++)c=I[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var K=Array.prototype,L=K.indexOf?function(a,b,c){return K.indexOf.call(a,b,c)}:function(a,b,c){c=c==h?0:0>c?Math.max(0,a.length+c):c;if(q(a))return!q(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},M=K.forEach?function(a,b,c){K.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=q(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)};var N=w,s="twig_ui_"+Math.floor(2147483648*Math.random()).toString(36);function O(a){return h===a||i===a||void 0===a||0===a?g:P(a)?0===Q(a):i}function R(a,b){J.apply(h,Array.prototype.slice.call(arguments,0));return a}function P(a){return p(a)||q(a)||r(a)}function Q(a){if(p(a))return a.length;if(q(a))return a.length;if(r(a)){var b=0,c;for(c in a)b++;return b}throw Error(typeof a+" is not countable.");}function S(a,b,c){if(p(a))M(a,b,c);else for(var d in a)b.call(c,a[d],d,a)};function T(a){this.env_=a;this.b=[];this.k={}}j=T.prototype;j.n=function(){return this.b};j.r=function(a){this.b=a};j.v=function(a){this.k=a};j.getParent=function(a){a=this.getParent_(a);return i===a?i:this.env_.d(a)};j.q=function(a,b,c){if(a in this.k){var d=new G;this.k[a](d,b,c||{});return d.toString()}d=this.getParent(b);if(i!==d)return d.i(a,b,c);throw Error("The template '"+this.w()+"' has no parent, and no trait defining the block '"+a+"'.");};
j.i=function(a,b,c){if(c&&a in c){var d=new G,f=c[a];delete c[a];f(d,b,c);return d.toString()}if(a in this.b)return d=new G,this.b[a](d,b,c),d.toString();d=this.getParent(b);return i!==d?d.i(a,b,c):""};j.h=function(a,b){var c=new G;this.render_(c,a||{},b||{});return c.toString()};function U(){this.f={};this.g={};this.j={};this.e={};this.l={}}j=U.prototype;j.h=function(a,b){var c=this.d(a);return c.h.call(c,R({},this.l,b||{}))};j.filter=function(a,b,c){if(!(a in this.f))throw Error("The filter '"+a+"' does not exist.");return this.f[a].apply(h,Array.prototype.slice.call(arguments,1))};j.p=function(a,b,c){if(!(a in this.g))throw Error("The function '"+a+"' does not exist.");return this.g[a].apply(h,Array.prototype.slice.call(arguments,1))};
j.test=function(a,b,c){if(!(a in this.j))throw Error("The test '"+a+"' does not exist.");return this.j[a].apply(h,Array.prototype.slice.call(arguments,1))};j.s=function(a,b){this.f[a]=b};j.t=function(a,b){this.g[a]=b};j.u=function(a,b){this.j[a]=b};j.o=function(){return this.l};j.d=function(a){var b=a[s]||(a[s]=++t);if(b in this.e)return this.e[b];a=new a(this);return this.e[b]=a};function V(a){this.m=a}V.prototype.toString=function(){return this.m};window.Twig=new U;x("goog.provide",function(a){m(a)});x("twig.attr",function(a,b,c,d,f){d=d||"any";f=void 0!==f?f:i;if(!r(a)&&!p(a))return f?i:h;if(b in a){if("array"!==d&&"function"==n(a[b]))return f?g:a[b].apply(a,c||[]);if("method"!==d)return f?g:a[b]}if("array"===d||p(a))return f?i:h;var b=b.toLowerCase(),e="get"+b,l="is"+b;return(b=H(a,function(a,b){b=b.toLowerCase();return b===e||b===l}))&&"function"==n(a[b])?f?g:a[b].apply(a,c||[]):f?i:h});x("twig.bind",N);
x("twig.inherits",function(a,b){function c(){}c.prototype=b.prototype;a.z=b.prototype;a.prototype=new c});x("twig.extend",R);x("twig.spaceless",function(a){return a.replace(/>[\s\xa0]+</g,"><").replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")});x("twig.range",function(a,b){for(var c=[];a<=b;a+=1)c.push(a);return c});x("twig.contains",function(a,b){var c;if(p(a))c=0<=L(a,b);else if(q(a))c=-1!=a.indexOf(b);else a:{for(c in a)if(a[c]==b){c=g;break a}c=i}return c});x("twig.countable",P);x("twig.count",Q);
x("twig.forEach",S);x("twig.empty",O);x("twig.createObj",function(a){for(var b={},c=0;c<arguments.length;c+=2)b[arguments[c]]=arguments[c+1];return b});x("twig.filter.capitalize",function(a,b){return b.charAt(0).toUpperCase()+b.substring(1)});
x("twig.filter.escape",function(a,b,c,d,f){if(f&&b instanceof V)return b.toString();b=b==h?"":""+b;if("js"===c){a=""+b;if(a.quote)b=a.quote();else{b=['"'];for(c=0;c<a.length;c++){var e=a.charAt(c),l=e.charCodeAt(0),d=b,f=c+1,o;if(!(o=D[e])){if(!(31<l&&127>l))if(e in E)e=E[e];else if(e in D)e=E[e]=D[e];else{l=e;o=e.charCodeAt(0);if(31<o&&127>o)l=e;else{if(256>o){if(l="\\x",16>o||256<o)l+="0"}else l="\\u",4096>o&&(l+="0");l+=o.toString(16).toUpperCase()}e=E[e]=l}o=e}d[f]=o}b.push('"');b=b.join("")}return b.substring(1,
b.length-1)}if(!c||"html"===c)return a=b,C.test(a)&&(-1!=a.indexOf("&")&&(a=a.replace(y,"&amp;")),-1!=a.indexOf("<")&&(a=a.replace(z,"&lt;")),-1!=a.indexOf(">")&&(a=a.replace(A,"&gt;")),-1!=a.indexOf('"')&&(a=a.replace(B,"&quot;"))),a;throw Error("The type '"+c+"' is not supported.");});x("twig.filter.length",function(a,b){return Q(b)});x("twig.filter.def",function(a,b){return O(a)?b||"":a});x("twig.filter.replace",function(a,b){for(var c in b)a=a.replace(RegExp(c,"g"),b[c]);return a});
x("twig.filter.join",function(a,b){var c=b||"",d=new G,f=g;S(a,function(a){f||d.append(c);f=i;d.append(a)});return d.toString()});x("twig.filter.keys",function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b});x("twig.filter.upper",function(a,b){return b.toUpperCase()});x("twig.filter.lower",function(a,b){return b.toLowerCase()});x("twig.StringBuffer",G);G.prototype.append=G.prototype.append;G.prototype.toString=G.prototype.toString;U.prototype.createTemplate=U.prototype.d;U.prototype.filter=U.prototype.filter;
U.prototype.invoke=U.prototype.p;U.prototype.test=U.prototype.test;U.prototype.setFilter=U.prototype.s;U.prototype.setFunction=U.prototype.t;U.prototype.setTest=U.prototype.u;U.prototype.render=U.prototype.h;U.prototype.getGlobals=U.prototype.o;x("twig.Template",T);T.prototype.setTraits=T.prototype.v;T.prototype.setBlocks=T.prototype.r;T.prototype.getBlocks=T.prototype.n;T.prototype.renderParentBlock=T.prototype.q;T.prototype.renderBlock=T.prototype.i;x("twig.Markup",V);})();
